spring.application.name=api

spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=none

# spring.liquibase.parameters.

org.terabudget.authentication.accessTokenExpirationMs=3600000
org.terabudget.authentication.refreshTokenExpirationMs=86400000

# Authentication
spring.liquibase.parameters.ui-client-id=a0c09875-f2cd-4f42-a008-de98cd066535
